// <auto-generated />
using BettingGames;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BettingGames.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20181030092135_AddingDB")]
    partial class AddingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BettingGames.Model.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryName")
                        .IsRequired();

                    b.Property<int>("SportID");

                    b.HasKey("ID");

                    b.HasIndex("SportID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("BettingGames.Model.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("EventName")
                        .IsRequired();

                    b.Property<int>("TournamentID");

                    b.HasKey("ID");

                    b.HasIndex("TournamentID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BettingGames.Model.Sport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SportName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("BettingGames.Model.Tournament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryID");

                    b.Property<string>("CountryName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("BettingGames.Model.Country", b =>
                {
                    b.HasOne("BettingGames.Model.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingGames.Model.Event", b =>
                {
                    b.HasOne("BettingGames.Model.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingGames.Model.Tournament", b =>
                {
                    b.HasOne("BettingGames.Model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
