// <auto-generated />
using BettingGames;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BettingGames.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20181113134147_AddBetandMarket")]
    partial class AddBetandMarket
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BettingGames.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryName")
                        .IsRequired();

                    b.Property<int>("SportID");

                    b.Property<string>("SportName");

                    b.Property<bool>("isHidden");

                    b.HasKey("ID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("BettingGames.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryID");

                    b.Property<string>("CountryName");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EventName")
                        .IsRequired();

                    b.Property<int>("SportID");

                    b.Property<string>("SportName");

                    b.Property<int>("TournamentID");

                    b.Property<string>("TournamentName");

                    b.Property<bool>("isHidden");

                    b.HasKey("ID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BettingGames.Model.BetType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BetName");

                    b.Property<int>("EventID");

                    b.HasKey("id");

                    b.ToTable("BetTypes");
                });

            modelBuilder.Entity("BettingGames.Model.Market", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BetID");

                    b.Property<string>("MarketName");

                    b.Property<decimal>("Odds");

                    b.Property<decimal>("Stake");

                    b.HasKey("id");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("BettingGames.Sport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SportName")
                        .IsRequired();

                    b.Property<bool>("isHidden");

                    b.HasKey("ID");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("BettingGames.Tournament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryID");

                    b.Property<string>("CountryName");

                    b.Property<int>("SportID");

                    b.Property<string>("SportName");

                    b.Property<string>("TournamentName")
                        .IsRequired();

                    b.Property<bool>("isHidden");

                    b.HasKey("ID");

                    b.ToTable("Tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
